variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_FOLDER: "android-sdk-linux"

before_script:
  - export ANDROID_HOME=~/$ANDROID_SDK_FOLDER
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/:$ANDROID_HOME/tools/bin/
  - echo y | sdkmanager --verbose "extras;android;m2repository"
  - echo y | sdkmanager --verbose "extras;google;google_play_services"
  - echo y | sdkmanager --verbose "extras;google;m2repository"
  - echo y | sdkmanager --verbose "platforms;android-$ANDROID_COMPILE_SDK"
  - echo y | sdkmanager --verbose "build-tools;$ANDROID_BUILD_TOOLS"
  - chmod +x ./gradlew

stages:
  - test
  - build

unitTests:
  stage: test
  script:
    - /usr/local/bin/fastlane unit_test
  tags:
    - android

compile:
  stage: build
  script:
    - /usr/local/bin/fastlane build_debug
  tags:
    - android
  artifacts:
    paths:
    - build/apk/
    expire_in: 1 week
    