language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository

script: 
- "./gradlew clean"

jobs:
  include:
    - stage: test
      script: "/gradlew testDebugUnitTest"
    - stage: build
      script: "./build-apk.sh"